apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flowops-hpa
  namespace: flowops
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flowops
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60   # wait 1 min before scaling up again
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300  # wait 5 min before scaling down (prevents thrash)
      policies:
        - type: Pods
          value: 1
          periodSeconds: 120
